# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
  
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: build/reports/tests
        
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: payment-api-0.0.1-${{ github.run_number }}.jar
        path: build/libs/payment-api-0.0.1-SNAPSHOT.jar 

  clean:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Clean Workspace
      uses: AutoModality/action-clean@v1.1.0

